[2025-07-05T19:39:24.958+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T19:39:25.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2025-07-05T19:39:25.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2025-07-05T19:39:25.067+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-05T19:39:25.096+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-02-05 00:00:00+00:00
[2025-07-05T19:39:25.119+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7263) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-05T19:39:25.120+0000] {standard_task_runner.py:63} INFO - Started process 7286 to run task
[2025-07-05T19:39:25.120+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fin_cotacoes_bcb_classic', 'transform', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/cotacoes.py', '--cfg-path', '/tmp/tmpualvbnxm']
[2025-07-05T19:39:25.122+0000] {standard_task_runner.py:91} INFO - Job 266: Subtask transform
[2025-07-05T19:39:25.228+0000] {task_command.py:426} INFO - Running <TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2024-02-05T00:00:00+00:00 [running]> on host 20adb53d65c4
[2025-07-05T19:39:25.380+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fin_cotacoes_bcb_classic' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-05T00:00:00+00:00'
[2025-07-05T19:39:25.382+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T19:39:25.382+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T19:39:25.383+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/cotacoes.py", line 52, in transform
    cotacoes = kwargs['ti'].xcom_pull(task_id='extract')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2025-07-05T19:39:25.406+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fin_cotacoes_bcb_classic, task_id=transform, run_id=scheduled__2024-02-05T00:00:00+00:00, execution_date=20240205T000000, start_date=20250705T193925, end_date=20250705T193925
[2025-07-05T19:39:25.441+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 266 for task transform (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 7286)
[2025-07-05T19:39:25.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-05T19:39:25.487+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
